function interfata(A1,A2,A3,R,R1,R2,R3,f,N,s)
 
figure('Name', 'Amplificatoare de instrumentatie',...
             'Numbertitle', 'off',...
             'Units', 'normalized',...
             'Position', [0.1 0.1 0.8 0.75]); 

uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.365 0.9 0.3 0.05],...
'FontSize',18,...
'foregroundcolor','black',...
'String','Amplificator de instrumentatie');
 
 
Bg1=uipanel('Title','Parametrii circuitului',...
    'Titleposition','Centertop',...
    'Position',[0.26 0.55 0.2 0.32],...
    'Backgroundcolor',[0.75,0.75,0.75]',...
    'Foregroundcolor','black',...
    'Fontsize',10);
 
Bg2=uipanel('Title','Semnal de intrare',...
    'Titleposition','Centertop',...
    'Position',[0.56 0.55 0.2 0.32],...
    'Backgroundcolor',[0.75,0.75,0.75]',...
    'Foregroundcolor','black',...
    'Fontsize',10);

 
uicontrol('Style','text',... 
'Units','normalized',...
'Position',[0.3 0.8 0.2 0.1],...
'backgroundcolor',[0.75,0.75,0.75],...
'string','R [kOhm]',...
'parent',Bg1);
 
 
uicontrol('Style','edit',... 
'Units','normalized',...
'Position',[0.5 0.8 0.25 0.1],...
'String',R,...
'Callback','R=str2num(get(gco,''String''));close;interfata(A1,A2,A3,R,R1,R2,R3,f,N,s)',...
'parent',Bg1);

uicontrol('Style','text',... 
'Units','normalized',...
'Position',[0.27 0.6 0.23 0.1],...
'backgroundcolor',[0.75,0.75,0.75],...
'string','R1 [kOhm]',...
'parent',Bg1);
 
 
uicontrol('Style','edit',... 
'Units','normalized',...
'Position',[0.5 0.6 0.25 0.1],...
'String',R1,...
'Callback','R1=str2num(get(gco,''String''));close;interfata(A1,A2,A3,R,R1,R2,R3,f,N,s)',...
'parent',Bg1);
 
uicontrol('Style','text',... 
'Units','normalized',...
'Position',[0.27 0.4 0.23 0.1],...
'backgroundcolor',[0.75,0.75,0.75],...
'string','R2 [kOhm]',...
'parent',Bg1);

uicontrol('Style','edit',... 
'Units','normalized',...
'Position',[0.5 0.4 0.25 0.1],...
'String',R2,...
'Callback','R2=str2num(get(gco,''String''));close;interfata(A1,A2,A3,R,R1,R2,R3,f,N,s)',...
'parent',Bg1);


uicontrol('Style','text',... 
'Units','normalized',...
'Position',[0.27 0.2 0.23 0.1],...
'backgroundcolor',[0.75,0.75,0.75],...
'string','R3 [kOhm]',...
'parent',Bg1);

uicontrol('Style','edit',... 
'Units','normalized',...
'Position',[0.5 0.2 0.25 0.1],...
'String',R3,...
'Callback','R3=str2num(get(gco,''String''));close;interfata(A1,A2,A3,R,R1,R2,R3,f,N,s)',...
'parent',Bg1);

uicontrol('Style','text',... 
'Units','normalized',...
'Position',[0.15 0.05 0.75 0.1],...
'backgroundcolor',[0.75,0.75,0.75],...
'string','R1 = R1*; R2 = R2*; R3 = R3*',...
'parent',Bg1);

 if R<1 || R1<1 || R2<1 || R3<1
 msgbox("Rezistentele nu pot fi egale cu 0 (zero) !!"+newline+"Reintroduceti valoarea!","Eroare","error");
 end


uicontrol('Style','text',... 
'Units','normalized',...
'Position',[0.3 0.2 0.15 0.1],...
'backgroundcolor',[0.75,0.75,0.75],...
'string','F [kHz]',...
'parent',Bg2);
 
uicontrol('Style','edit',...
'Units','normalized',...
'Position',[0.45 0.2 0.25 0.1],...
'String',f,...
'Callback','f=str2num(get(gco,''String''));close;interfata(A1,A2,A3,R,R1,R2,R3,f,N,s)',...
'parent',Bg2);

uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.2 0.8 0.35 0.1],...
'backgroundcolor',[0.75,0.75,0.75],...
'string','Alimentare AO[V]',...
'parent',Bg2);
 
uicontrol('Style','edit',... 
'Units','normalized',...
'Position',[0.6 0.8 0.25 0.1],...
'String',A3,...
'Callback','A3=str2num(get(gco,''String''));close;interfata(A1,A2,A3,R,R1,R2,R3,f,N,s)',...
'parent',Bg2); 

 uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.3 0.6 0.15 0.1],...
'backgroundcolor',[0.75,0.75,0.75],...
'string','A1 [V]',...
'parent',Bg2);
 
uicontrol('Style','edit',... 
'Units','normalized',...
'Position',[0.45 0.6 0.25 0.1],...
'String',A1,...
'Callback','A1=str2num(get(gco,''String''));close;interfata(A1,A2,A3,R,R1,R2,R3,f,N,s)',...
'parent',Bg2);

 
 if A1>A3 
       msgbox("A1[V] nu poate fi mai mare decat Alimentarea AO[V]!"+newline+"Reintroduceti valoarea!","Eroare","error");
       
 else    
 

uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.3 0.4 0.15 0.1],...
'backgroundcolor',[0.75,0.75,0.75],...
'string','A2 [V]',...
'parent',Bg2);
 
uicontrol('Style','edit',... 
'Units','normalized',...
'Position',[0.45 0.4 0.25 0.1],...
'String',A2,...
'Callback','A2=str2num(get(gco,''String''));close;interfata(A1,A2,A3,R,R1,R2,R3,f,N,s)',...
'parent',Bg2); 

if  A2>A3
    
      msgbox("A2[V] nu poate fi mai mare decat Alimentarea AO[V]!"+newline+"Reintroduceti valoarea!","Eroare","error");
      
end
 end
 



uicontrol('Style','PopupMenu',...
               'Units','normalized',...
               'Position',[0.22 0.05 0.6 0.1],...
               'Value',s,...
               'String','Sinusoidal|Triunghiular',...
               'Callback','s=get(gco,''Value'');close;interfata(A1,A2,A3,R,R1,R2,R3,f,N,s)',...
               'parent', Bg2);
 


if R>=1 && R1>=1 && R2>=1 && R3>=1
    if A1<=A3 && A2<=A3 
 
 
T=1/f;
t=0:T/1000:N*T;
 
    switch s
    case 1
 
Vi1=A1*sin(2*3.14*f*t);
Vi2=A2*sin(2*3.14*f*t);
 
    case 2
Vi1=(2.*A1./pi).*asin(sin(2*3.14*f*t));
Vi2=(2.*A2./pi).*asin(sin(2*3.14*f*t));

    end 
 
    
poza=imread('Circuit.png');
image(poza);
set(gca,'Position',[0.56 0.1 0.4 0.4])
title('Amplificator de instrumentatie')
axis off;
 
AMP=(1+(2*R1/R))*(R3/R2);
Vi=(Vi1-Vi2);


 for i=1:length(t)
            Vo(i)= Vi(i).*AMP;
            if Vo(i)>=A3
                Vo(i)=A3; 
            elseif Vo(i)<=-A3
                Vo(i)=-A3; 
            else
                
            end
  end

subplot('position',[0.06 0.1 0.4 0.4]);
plot(t,Vi1,'-r');
hold on;
plot(t,Vi2,'-g');
hold on;

plot(t,Vo,'-b');
hold on; 

grid on;
title('Vi1 Vi2 si Vo');
xlabel('timp [s]');
ylabel('Amplitudine [V]');
legend('Vi1','Vi2','Vo');
 
 
 
 uimenu('Label', 'Documentatie',...
                  'checked', 'on',...
                  'Foregroundcolor', [0.1 0.1 0.1],...
                  'Callback', 'open(''Proiect_GAC-VidicanMihai.pdf'')');         

    end 
end 
   
